### PR TITLE
Add more Go versions, for time being only for Fedora

### PR DESCRIPTION
**Pull request by jcajka**
Add more Go versions for now just for Fedora. Added one test case. And some related minor bugfixes and enhancement.

### CODE REVIEW

**Comment by jcajka** [comment]
Updated the README file.

**Comment by omron93** [comment]
It looks good. Thanks.

Two suggestions:
- to prevent git history (changes of a file) in one place see https://github.com/sclorg/welcome/blob/master/contribution.md#adding-a-new-version . But golang don't have rich history yet, so IMHO if you don't have time to do it, it's not necessary.

- `test/run` script can be shared. In version directory place symlink to ../test. And one copy of test script could be in root directory. To test a correct version `VERSION` variable could be used - https://github.com/sclorg/mariadb-container/blob/master/test/run#L355

Otherwise it seems good.

**Comment by jcajka** [comment]
Restructured tests so they are shared(they should pass on all images). Squashed the commits. If you don't mind I don't see any value in "preserving" history as I believe there is non.

**Comment by omron93** [comment]
[test][test-openshift]

**Comment by omron93** [comment]
[test][test-openshift]

**Comment by omron93** [comment]
`registry.fedoraproject.org/f28/s2i-base` is missing. I've tried to build it, but there is some build error. I'll try again tomorrow...

**Comment by jcajka** [comment]
@omron93 Yes f28 images are not yet available.

**Comment by omron93** [comment]
> Yes f28 images are not yet available. It is bit weird practice that the image is available only after the release...

@jcajka Do you have more information about this? `fedora:28` base image is available, so I thought that problem with building `s2i-core` container is on my side.

**Comment by jcajka** [comment]
@omron93 yeah, you are right is seems that regular base images are available but the base-s2i(and I guess other layered images) are not yet available/built based on the https://registry.fedoraproject.org/

**Comment by AlessandroMenti** [comment]
@jcajka @omron93 The `f28/base-s2i` images are available on Fedora now.

I've also noticed that, starting from Go 1.10, [the `pkg` directory is not created anymore; instead, an internal cache is used](https://golang.org/doc/go1.10#build). Its path is [`$XDG_CACHE_HOME/go-build` or `$HOME/.cache/go-build`](https://go-review.googlesource.com/c/go/+/68116/6/src/cmd/go/internal/cache/default.go#55), so, I suggest altering the `assemble` and `save-artifacts` scripts as follows:

`assemble`:
```
...
        echo "Assembling GOPATH"

        export GOPATH=`realpath $HOME/go`

        mkdir -p $GOPATH/src/$IMPORT_URL

        mv /tmp/src/* $GOPATH/src/$IMPORT_URL

        if [[ -d /tmp/artifacts/go-build ]]; then

            echo "Restoring previous build artifacts"

            if [[ -n "$XDG_CACHE_HOME" ]]; then

                CACHEDIR="$XDG_CACHE_HOME"

            else

                CACHEDIR="$HOME/.cache"

            fi

            mkdir -p $CACHEDIR

            mv /tmp/artifacts/go-build $CACHEDIR/

        fi
...
```

`save-artifacts`:
```
#!/bin/bash

set -e

if [[ -n "$XDG_CACHE_HOME" ]]; then

    CACHEDIR="$XDG_CACHE_HOME"

else

    CACHEDIR="$HOME/.cache"

fi

if [[ -d $CACHEDIR/go-build ]]; then

    pushd $CACHEDIR &> /dev/null

    tar -cf - go-build

    popd &> /dev/null

fi
```

(Since I have prepared the SCL RPMs for Go 1.10 and am in the process of releasing them, let me know when this PR is merged and I'll add the RHEL 7-based containers).

**Comment by AlessandroMenti** [comment]
@jcajka @omron93 Since I am not an administrator, could you please trigger the Fedora Jenkins build again? I'd like, if possible, to see this PR merged so that I can build mine on top of it for CentOS and RHEL.

**Comment by jcajka** [comment]
[test][test-openshift]

**Comment by jcajka** [comment]
[test][test-openshift]

**Comment by jcajka** [comment]
@omron93 Could you please take a look and merge this? All test should be passing now, but it seems that the Fedora set didn't get scheduled.
@AlessandroMenti I have added the support for the cache, I have used bit different implementation than you. I have leveraged the go env.

**Comment by omron93** [comment]
[test][test-openshift]

**Comment by omron93** [comment]
@jcajka To be able to trigger CI tests run in CentOS infrastructure (centos + fedora images), you have to be **public** member of `sclorg/` organization.

Tests for rhel7 and centos7 are failing because of
```
ERROR[/bin/bash -c go version] Expected 'go1.8', got 'go version go1.10.2 linux/amd64
```
@jcajka Could you please fix it? I'm not sure what's the right solution... (bacause these Dockerfiles lives in `1.8/` folder)

**Comment by jcajka** [comment]
@omron93 I don't know what is going on in the RHEL and CentOS and I don't know what is expected. Maybe deparker and tstelar(already contacted them) will know, but I don't see any reason to block this PR on it(or even fix it, it should be separate to these changes).

**Comment by omron93** [comment]
> I don't see any reason to block this PR on it

Good point. All changes look good, so merging.

**Pull request merged**
