### PR TITLE
Add Go 1.11 image for now just for Fedora

### PR DESCRIPTION
**Pull request by jcajka**

### CODE REVIEW

**Comment by jcajka** [comment]
@omron93 it seems that the centos ci is broken
```
09:17:24 + ssh -F ssh_config host yum -y install docker perl git centos-release-scl-rh rsync golang-github-cpuguy83-go-md2man groff-base centos-release-openshift-origin epel-release
09:17:24 ssh: Could not resolve hostname .ci.centos.org: Name or service not known
```
Bad config?? dns??

**Comment by omron93** [comment]
> Bad config?? dns??

I guess some race problem with fedora job (both are started at the same time). Retrying the job usually helps.

**Comment by omron93** [comment]
LGTM, thanks.

1.11/ is same as older versions. Only root README needs to be updated (add 1.11 and remove EOLed F26).

[test-openshift]

**Comment by omron93** [comment]
Proposed README fixes are in #13

**Pull request merged**
