### PR TITLE
Add aarch64 imagestreams

### PR DESCRIPTION
**Pull request by yselkowitz**

### CODE REVIEW

**Comment by rhscl-automation-poll** [comment]
Can one of the admins verify this patch?

**Comment by rhscl-automation-poll** [comment]
Can one of the admins verify this patch?

**Comment by rhscl-automation-poll** [comment]
Can one of the admins verify this patch?

**Comment by yselkowitz** [comment]
@hhorak could this one be reviewed too?

**Comment by hhorak** [comment]
Tested manually by importing to OCP 4.6, LGTM.

**Pull request merged**
