### PR TITLE
Update imagestreams for 1.14.7 in UBI8

### PR DESCRIPTION
**Pull request by yselkowitz**

### CODE REVIEW

**Comment by rhscl-automation-poll** [comment]
Can one of the admins verify this patch?

**Comment by rhscl-automation-poll** [comment]
Can one of the admins verify this patch?

**Comment by rhscl-automation-poll** [comment]
Can one of the admins verify this patch?

**Comment by rhscl-automation-poll** [comment]
Can one of the admins verify this patch?

**Review by jcajka — APPROVED** [review]
LGTM

**Pull request merged**
