### PR TITLE
Add naive incremental build tests

### PR DESCRIPTION
**Pull request by jcajka**
Add the incremental build tests as promised.

### CODE REVIEW

**Comment by omron93** [comment]
[test]

**Comment by omron93** [comment]
I've tried on my laptop and sometimes incremental build failed (import-with-vendor-app)

```
$ IMAGE_NAME=centos/go-toolset-7-centos7 ./s2i-build-incremental 
I1208 15:24:19.289119 22568 clone.go:32] Downloading "/home/mskalick/Packages/docker/sclorg/golang-container/1.8/test/import-with-vendor-app/app" ...
I1208 15:24:19.315601 22568 install.go:251] Using "assemble" installed from "image:///usr/libexec/s2i/assemble"
I1208 15:24:19.315642 22568 install.go:251] Using "run" installed from "image:///usr/libexec/s2i/run"
I1208 15:24:19.315662 22568 install.go:251] Using "save-artifacts" installed from "image:///usr/libexec/s2i/save-artifacts"
E1208 15:24:20.652695 22568 tar.go:321] Error extracting file "pkg/linux_amd64/github.com/cpuguy83/go-md2man/md2man.a": unexpected EOF
E1208 15:24:20.652731 22568 tar.go:333] Error extracting tar stream
W1208 15:24:21.632528 22568 sti.go:160] Clean build will be performed because of error saving previous build artifacts
/tmp/src ~
~
```

But this is random and not often :-(

@jcajka Do you have any idea what could cause this?

**Comment by omron93** [comment]
[test]

**Comment by hhorak** [comment]
It works ok repeatadly on my machine.. LGTM

**Pull request merged**
